export const paths = {
  signIn: "/",
  home: "/home",
  users: "/users",
  edit: "/edit",
  product: "/product",
  profile: "/profile",
  profile2: "/profile2",
  profile3: "/profile3",
  profile4: "/profile4",
  profile5: "/profile5",
  profile6: "/profile6",
  profile7: "/profile7",
  profile8: "/profile8",
  profile9: "/profile9",
  profile10: "/profile10",
  profile11: "/profile11",
};
